### PR TITLE
Directory Tree v1.0.0

### LINKED ISSUE #15: Only directory not files like `tree -d` in bash
Is there a way to only display directory not files like `tree -d` in bash ? 
Could you please describe how to use pattern as well ?

### PR DESCRIPTION
**Pull request by rahulbordoloi**
# Directory Tree v1.0.0

* Aliasing `DisplayTree` as Entrypoint
* Check Version Support
* Raise Exception Support
* Print Traceback Support
* Docs (Contributing & Security)
* Improving Imports, Type Hinting and Separating Out Driver and Logic
* Support to Filter Only Directories / Files as per Requirement (#15)
* Parameter to Show Files or Directories First (#17)
* Package CLI Support, Improved ignoreList Support (#15)

Closes #15, #17

### CODE REVIEW

**Review by rahulbordoloi — COMMENTED** [review]
LGTM!

**Comment by rahulbordoloi** [comment]
Testing on Platform(s): 
1. **Mac** - :white_check_mark: (M2 Pro, Sonoma 14.6.1)
2. **Windows** - :white_check_mark: (Ryzen 9 4000, Windows 10)
3. **Linux** - TBD

**Review by rahulbordoloi — COMMENTED** [review]
Checked & Tested in All Envs

**Review by DevAccountForR-07 — APPROVED** [review]
GTG!

**Pull request merged**
